<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>BENNUGD SCRIPTING DICTIONARY – By Adrián Melián: Version 0.0.1</string>
	<key>fileTypes</key>
	<array>
		<string>prg</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>PRG</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.prg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.prg</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.prg</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.prg</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.prg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*((?i:function|process))\s*([a-zA-Z_]\w*)\s*(\()([^)]*)(\)).*\n?</string>
			<key>name</key>
			<string>meta.function.prg</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=[//])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.prg</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.prg</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.apostrophe.prg</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=REM )</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.prg</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>REM </string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.prg</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.rem.prg</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Begin|If|Then|Else|ElseIf|End|While|Switch|For|To|Each|In|Step|Case|Return|Repeat|Continue|Do|Until|Loop|Next|With|Break)\b)</string>
			<key>name</key>
			<string>keyword.control.prg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=|&gt;=|&lt;|&gt;|&lt;|&lt;&gt;|==|!=|&&|\|\||\+|-|\*|\^|&amp;|\b(?i:(Mod|And|Not|Or|Xor|Is))\b</string>
			<key>name</key>
			<string>keyword.operator.prg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Class|Const|Redim|Function|Process|Declare|End|Randomize|OnExit|Global|Struct|Local)\b)</string>
			<key>name</key>
			<string>storage.type.prg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Private|Public|Default)\b)</string>
			<key>name</key>
			<string>storage.modifier.prg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Empty|False|Nothing|Null|True)\b)</string>
			<key>name</key>
			<string>constant.language.prg</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.prg</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"(?!")</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.prg</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.prg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>""</string>
					<key>name</key>
					<string>constant.character.escape.apostrophe.prg</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.prg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\$)[a-zA-Z_x7f-xff][a-zA-Z0-9_x7f-xff]*?\b</string>
			<key>name</key>
			<string>variable.other.prg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(DEFINE|Import|Include)\b)</string>
			<key>name</key>
			<string>support.class.prg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Contents|StaticObjects|ClientCertificate|Cookies|Form|QueryString|ServerVariables)\b)</string>
			<key>name</key>
			<string>support.class.collection.prg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(TotalBytes|Buffer|CacheControl|Charset|ContentType|Expires|ExpiresAbsolute|IsClientConnected|PICS|Status|ScriptTimeout|CodePage|LCID|SessionID|Timeout)\b)</string>
			<key>name</key>
			<string>support.constant.prg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(SetAbort|SetComplete|BianryRead|AddHeader|AppendToLog|BinaryWrite|Clear|End|Flush|Redirect|Write|CreateObject|HTMLEncode|MapPath|URLEncode|Abandon)\b)</string>
			<key>name</key>
			<string>support.function.prg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Frame|Set_fps|Fps|Signal|Clear_Screen|Delete_Text|Say|load_fnt|load_fpg|SET_WAV_VOLUME|Key|ftoa|itoa|Asc|Atof|Atoi|Chr|Find|Format|Lcase|Len|Lpad|Rpad|Strcasecmp|Strlen|Strrev|Substr|Trim|Ucase|Abs|Acos|Asin|Atan|Atan2|Cos|Fget_angle|Fget_dist|Finite|Get_distx|Get_disty|Isinf|Isnan|Near_angle|Pow|Sin|Sqrt|Tan)\b)</string>
			<key>name</key>
			<string>support.function.event.prg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Byte|Array|Char|Float|Int|String|File|Graph|X|Y|Z|Alpha|Priority)\b)</string>
			<key>name</key>
			<string>support.function.vb.prg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f)?\b</string>
			<key>name</key>
			<string>constant.numeric.prg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(os_id|S_FREEZE|S_KILL|vbcrlf|vbformfeed|vblf|vbnewline|vbnullchar|vbnullstring|vbtab|vbverticaltab|vbbinarycompare|vbtextcomparevbsunday|vbmonday|vbtuesday|vbwednesday|vbthursday|vbfriday|vbsaturday|vbusesystemdayofweek|vbfirstjan1|vbfirstfourdays|vbfirstfullweek|vbgeneraldate|vblongdate|vbshortdate|vblongtime|vbshorttime|vbobjecterror|vbEmpty|vbNull|vbInteger|vbLong|vbSingle|vbDouble|vbCurrency|vbDate|vbString|vbObject|vbError|vbBoolean|vbVariant|vbDataObject|vbDecimal|vbByte|vbArray)\b)</string>
			<key>name</key>
			<string>support.type.vb.prg</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.prg</string>
	<key>uuid</key>
	<string>291022B4-6B1D-11D9-90EB-000D93589AF6</string>
</dict>
</plist>
